# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xgboost.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'xgboost.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rxgboost.proto\"v\n\x0eXGBoostRequest\x12\x0b\n\x03\x64\x61y\x18\x01 \x01(\x05\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\r\n\x05light\x18\x03 \x01(\x02\x12\x10\n\x08humidity\x18\x04 \x01(\x02\x12\r\n\x05water\x18\x05 \x01(\x02\x12\x12\n\nplant_type\x18\x06 \x01(\x05\"I\n\x0fXGBoostResponse\x12\x11\n\tgrowth_cm\x18\x01 \x01(\x02\x12\x12\n\nleaf_count\x18\x02 \x01(\x02\x12\x0f\n\x07node_cm\x18\x03 \x01(\x02\x32\x41\n\x11XGBoostRegression\x12,\n\x07Predict\x12\x0f.XGBoostRequest\x1a\x10.XGBoostResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xgboost_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_XGBOOSTREQUEST']._serialized_start=17
  _globals['_XGBOOSTREQUEST']._serialized_end=135
  _globals['_XGBOOSTRESPONSE']._serialized_start=137
  _globals['_XGBOOSTRESPONSE']._serialized_end=210
  _globals['_XGBOOSTREGRESSION']._serialized_start=212
  _globals['_XGBOOSTREGRESSION']._serialized_end=277
# @@protoc_insertion_point(module_scope)
