// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: xgboost.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from xgboost.proto</summary>
public static partial class XgboostReflection {

  #region Descriptor
  /// <summary>File descriptor for xgboost.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static XgboostReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg14Z2Jvb3N0LnByb3RvInYKDlhHQm9vc3RSZXF1ZXN0EgsKA2RheRgBIAEo",
          "BRITCgt0ZW1wZXJhdHVyZRgCIAEoAhINCgVsaWdodBgDIAEoAhIQCghodW1p",
          "ZGl0eRgEIAEoAhINCgV3YXRlchgFIAEoAhISCgpwbGFudF90eXBlGAYgASgF",
          "IjgKD1hHQm9vc3RSZXNwb25zZRIRCglncm93dGhfY20YASABKAISEgoKbGVh",
          "Zl9jb3VudBgCIAEoAjJBChFYR0Jvb3N0UmVncmVzc2lvbhIsCgdQcmVkaWN0",
          "Eg8uWEdCb29zdFJlcXVlc3QaEC5YR0Jvb3N0UmVzcG9uc2ViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::XGBoostRequest), global::XGBoostRequest.Parser, new[]{ "Day", "Temperature", "Light", "Humidity", "Water", "PlantType" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::XGBoostResponse), global::XGBoostResponse.Parser, new[]{ "GrowthCm", "LeafCount" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class XGBoostRequest : pb::IMessage<XGBoostRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<XGBoostRequest> _parser = new pb::MessageParser<XGBoostRequest>(() => new XGBoostRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<XGBoostRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::XgboostReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public XGBoostRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public XGBoostRequest(XGBoostRequest other) : this() {
    day_ = other.day_;
    temperature_ = other.temperature_;
    light_ = other.light_;
    humidity_ = other.humidity_;
    water_ = other.water_;
    plantType_ = other.plantType_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public XGBoostRequest Clone() {
    return new XGBoostRequest(this);
  }

  /// <summary>Field number for the "day" field.</summary>
  public const int DayFieldNumber = 1;
  private int day_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Day {
    get { return day_; }
    set {
      day_ = value;
    }
  }

  /// <summary>Field number for the "temperature" field.</summary>
  public const int TemperatureFieldNumber = 2;
  private float temperature_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Temperature {
    get { return temperature_; }
    set {
      temperature_ = value;
    }
  }

  /// <summary>Field number for the "light" field.</summary>
  public const int LightFieldNumber = 3;
  private float light_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Light {
    get { return light_; }
    set {
      light_ = value;
    }
  }

  /// <summary>Field number for the "humidity" field.</summary>
  public const int HumidityFieldNumber = 4;
  private float humidity_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Humidity {
    get { return humidity_; }
    set {
      humidity_ = value;
    }
  }

  /// <summary>Field number for the "water" field.</summary>
  public const int WaterFieldNumber = 5;
  private float water_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Water {
    get { return water_; }
    set {
      water_ = value;
    }
  }

  /// <summary>Field number for the "plant_type" field.</summary>
  public const int PlantTypeFieldNumber = 6;
  private int plantType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PlantType {
    get { return plantType_; }
    set {
      plantType_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as XGBoostRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(XGBoostRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Day != other.Day) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Temperature, other.Temperature)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Light, other.Light)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Humidity, other.Humidity)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Water, other.Water)) return false;
    if (PlantType != other.PlantType) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Day != 0) hash ^= Day.GetHashCode();
    if (Temperature != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Temperature);
    if (Light != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Light);
    if (Humidity != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Humidity);
    if (Water != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Water);
    if (PlantType != 0) hash ^= PlantType.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Day != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Day);
    }
    if (Temperature != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(Temperature);
    }
    if (Light != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(Light);
    }
    if (Humidity != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(Humidity);
    }
    if (Water != 0F) {
      output.WriteRawTag(45);
      output.WriteFloat(Water);
    }
    if (PlantType != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(PlantType);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Day != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Day);
    }
    if (Temperature != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(Temperature);
    }
    if (Light != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(Light);
    }
    if (Humidity != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(Humidity);
    }
    if (Water != 0F) {
      output.WriteRawTag(45);
      output.WriteFloat(Water);
    }
    if (PlantType != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(PlantType);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Day != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Day);
    }
    if (Temperature != 0F) {
      size += 1 + 4;
    }
    if (Light != 0F) {
      size += 1 + 4;
    }
    if (Humidity != 0F) {
      size += 1 + 4;
    }
    if (Water != 0F) {
      size += 1 + 4;
    }
    if (PlantType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlantType);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(XGBoostRequest other) {
    if (other == null) {
      return;
    }
    if (other.Day != 0) {
      Day = other.Day;
    }
    if (other.Temperature != 0F) {
      Temperature = other.Temperature;
    }
    if (other.Light != 0F) {
      Light = other.Light;
    }
    if (other.Humidity != 0F) {
      Humidity = other.Humidity;
    }
    if (other.Water != 0F) {
      Water = other.Water;
    }
    if (other.PlantType != 0) {
      PlantType = other.PlantType;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Day = input.ReadInt32();
          break;
        }
        case 21: {
          Temperature = input.ReadFloat();
          break;
        }
        case 29: {
          Light = input.ReadFloat();
          break;
        }
        case 37: {
          Humidity = input.ReadFloat();
          break;
        }
        case 45: {
          Water = input.ReadFloat();
          break;
        }
        case 48: {
          PlantType = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Day = input.ReadInt32();
          break;
        }
        case 21: {
          Temperature = input.ReadFloat();
          break;
        }
        case 29: {
          Light = input.ReadFloat();
          break;
        }
        case 37: {
          Humidity = input.ReadFloat();
          break;
        }
        case 45: {
          Water = input.ReadFloat();
          break;
        }
        case 48: {
          PlantType = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class XGBoostResponse : pb::IMessage<XGBoostResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<XGBoostResponse> _parser = new pb::MessageParser<XGBoostResponse>(() => new XGBoostResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<XGBoostResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::XgboostReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public XGBoostResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public XGBoostResponse(XGBoostResponse other) : this() {
    growthCm_ = other.growthCm_;
    leafCount_ = other.leafCount_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public XGBoostResponse Clone() {
    return new XGBoostResponse(this);
  }

  /// <summary>Field number for the "growth_cm" field.</summary>
  public const int GrowthCmFieldNumber = 1;
  private float growthCm_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float GrowthCm {
    get { return growthCm_; }
    set {
      growthCm_ = value;
    }
  }

  /// <summary>Field number for the "leaf_count" field.</summary>
  public const int LeafCountFieldNumber = 2;
  private float leafCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float LeafCount {
    get { return leafCount_; }
    set {
      leafCount_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as XGBoostResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(XGBoostResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(GrowthCm, other.GrowthCm)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(LeafCount, other.LeafCount)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (GrowthCm != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(GrowthCm);
    if (LeafCount != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(LeafCount);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (GrowthCm != 0F) {
      output.WriteRawTag(13);
      output.WriteFloat(GrowthCm);
    }
    if (LeafCount != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(LeafCount);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (GrowthCm != 0F) {
      output.WriteRawTag(13);
      output.WriteFloat(GrowthCm);
    }
    if (LeafCount != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(LeafCount);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (GrowthCm != 0F) {
      size += 1 + 4;
    }
    if (LeafCount != 0F) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(XGBoostResponse other) {
    if (other == null) {
      return;
    }
    if (other.GrowthCm != 0F) {
      GrowthCm = other.GrowthCm;
    }
    if (other.LeafCount != 0F) {
      LeafCount = other.LeafCount;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          GrowthCm = input.ReadFloat();
          break;
        }
        case 21: {
          LeafCount = input.ReadFloat();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 13: {
          GrowthCm = input.ReadFloat();
          break;
        }
        case 21: {
          LeafCount = input.ReadFloat();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
